// ui/src/pages/Latency/components/LatencyTest/region.group.tsx
import React, { useEffect, useState } from 'react'

import { RegionGroupModel, RegionModel } from '@/models/region.model'

interface propsModel {
  regionsGroup: Array<RegionGroupModel>
  onRegionSelected?: (regionsGroup: RegionGroupModel[]) => void
  onRegionRemoved?: (regionsGroup: RegionModel[]) => void
  onRegionAdded?: (regionsGroup: RegionModel[]) => void
}

const RegionGroup = (props: propsModel) => {
  const styleVar = {
    fontSize: 'small'
  }

  const { regionsGroup, onRegionSelected, onRegionRemoved, onRegionAdded } = props
  const [regionsGroupState, setRegionsGroup] = useState(() => regionsGroup)
  const [totalCheckedRegions, setTotalCheckedRegions] = useState<number>(() => {
    const regions = regionsGroup.reduce((acc: RegionModel[], current: RegionGroupModel) => {
      const filtered = current.regions.filter((e) => e.checked)
      return acc.concat(filtered)
    }, [] as RegionModel[])

    return regions.length
  })

  const onAllSelect = (ev: RegionGroupModel) => {
    console.log(ev)
    ev.checked = !ev.checked
    ev.regions.forEach((el) => (el.checked = ev.checked))

    const index = regionsGroupState.findIndex((e) => e.geography === ev.geography)

    if (index > -1) {
      regionsGroupState[index] = ev
      setRegionsGroup([...regionsGroupState])
    }

    onRegionSelected?.call(null, regionsGroupState)

    if (!ev.checked) {
      onRegionRemoved?.call(null, ev.regions)
      setTotalCheckedRegions(totalCheckedRegions - ev.regions.length)
    } else {
      onRegionAdded?.call(null, ev.regions)
      setTotalCheckedRegions(totalCheckedRegions + ev.regions.length)
    }
  }

  const onPartialSelect = (region: RegionModel, group: RegionGroupModel) => {
    region.checked = !region.checked

    const regionIndex = group.regions.findIndex((e) => e.regionName === region.regionName)

    if (regionIndex > -1) {
      group.regions[regionIndex] = region
    }

    const index = regionsGroupState.findIndex((e) => e.geography === group.geography)

    if (index > -1) {
      regionsGroupState[index] = group
      setRegionsGroup([...regionsGroupState])
    }

    onRegionSelected?.call(null, regionsGroupState)

    if (!region.checked) {
      onRegionRemoved?.call(null, [region])
      setTotalCheckedRegions(totalCheckedRegions - 1)
    } else {
      onRegionAdded?.call(null, [region])
      setTotalCheckedRegions(totalCheckedRegions + 1)
    }
  }

  useEffect(() => {
    setRegionsGroup(regionsGroup)
  }, [regionsGroup])

  return (
    <>
      {totalCheckedRegions === 0 && (
        <div className="text-danger font-weight-bold">Please select regions to get started</div>
      )}
      {
        <div className="row mx-0 mt-2" style={styleVar}>
          {regionsGroupState.map((group, index) => {
            return (
              <div key={index} className="col-lg-4 pl-0 pr-2 mt-2">
                <div className="ft-14 border rounded-sm">
                  <div className="d-flex justify-content-between bg-light border-bottom p-2">
                    <strong>{group.geography}</strong>
                    <label className="mb-0" htmlFor={group.geography}>
                      <input
                        type="checkbox"
                        id={group.geography}
                        checked={group.checked}
                        onChange={(_) => onAllSelect(group)}
                      />
                      <span className="checkbox-header">Check all</span>
                    </label>
                  </div>
                  <div className="mt-1 px-3 py-2">
                    {group?.regions.map((region, index) => {
                      const checkedClass = region.checked ? 'text-primary' : ''
                      return (
                        <label
                          key={index}
                          htmlFor={region.regionName}
                          className={`cursor-pointer mr-3 mb-1 ${checkedClass}`}
                        >
                          <input
                            type="checkbox"
                            id={region.regionName}
                            checked={region.checked}
                            onChange={() => onPartialSelect(region, group)}
                          />
                          <span className="checkbox-item">{region.displayName}</span>
                        </label>
                      )
                    })}
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      }
    </>
  )
}

export default RegionGroup

// ClientApp/src/app/shared/region-group/region-group.component.ts
import { Component, OnInit } from '@angular/core'
import { DefaultRegionsKey, RegionModel } from '../../models'
import { RegionService } from '../../services'

interface RegionGroupModel {
  geography: string
  regions: RegionModel[]
  checked?: boolean
}

@Component({
  selector: 'app-region-group',
  templateUrl: './region-group.component.html'
})
export class RegionsComponent implements OnInit {
  regionsGroup: RegionGroupModel[] = []
  totalCheckedRegions = 0

  constructor(private regionService: RegionService) {
    const groups = this.regionService.getAllRegions().reduce((arr, item) => {
      if (!arr.includes(item.geography)) {
        arr.push(item.geography)
      }
      return arr
    }, [])

    this.regionsGroup = groups
      .reduce((arr, geography) => {
        const regions = this.regionService
          .getAllRegions()
          .filter((i) => i.geography === geography)
          .map((i) => ({ ...i, checked: false }))

        arr.push({ geography, checked: false, regions })
        return arr
      }, [])
      .sort((a, b) => {
        return b.regions.length - a.regions.length
      })
  }

  ngOnInit() {
    this.initRegions()
  }

  onChange(region: RegionModel, group: RegionGroupModel) {
    if (region) {
      this.checkRegion(region, group)
    } else {
      this.checkGroup(group)
    }

    const checkedRegions = this.getCheckedRegions()
    this.regionService.updateSelectedRegions(checkedRegions)
  }

  initRegions() {
    const res = localStorage.getItem(DefaultRegionsKey)
    const defaultRegions: RegionModel[] = res ? JSON.parse(res) : []

    if (Array.isArray(defaultRegions)) {
      this.regionsGroup.forEach((group) => {
        let isGroupChecked = true

        group.regions.forEach((item) => {
          const isDefault = defaultRegions.some(
            (i) => i.storageAccountName === item.storageAccountName
          )

          if (isDefault) {
            item.checked = true
            this.totalCheckedRegions++
          }

          if (!item.checked) {
            isGroupChecked = false
          }
        })

        group.checked = isGroupChecked
      })
    }
  }

  private checkRegion(region: RegionModel, group: RegionGroupModel) {
    const { checked } = region

    if (checked) {
      group.checked = group.regions.every((element) => element.checked)
    } else {
      group.checked = false
    }
  }

  private checkGroup(group: RegionGroupModel) {
    const { checked, regions } = group
    regions.forEach((i) => {
      i.checked = checked
    })
  }

  private getCheckedRegions() {
    return this.regionsGroup.reduce((arr, group) => {
      group.regions.forEach((region) => {
        if (region.checked) {
          arr.push(region)
        }
      })

      this.totalCheckedRegions = arr.length
      return arr
    }, [])
  }
}

<div>
  <section
    *ngIf="!totalCheckedRegions"
    class="alert alert-danger d-flex align-items-center"
    role="alert"
  >
    <strong>Please select at least one region to start test.</strong>
  </section>
  <div class="row gx-3">
    <div class="col-12 col-md-4 mt-3" *ngFor="let group of regionsGroup">
      <section class="border rounded">
        <div class="d-flex justify-content-between align-items-center bg-light border-bottom p-2">
          <strong>{{ group.geography }}</strong>
          <div class="form-check form-switch">
            <input
              class="form-check-input"
              type="checkbox"
              [id]="group.geography"
              [(ngModel)]="group.checked"
              (change)="onChange(null, group)"
            />
            <label class="form-check-label" [for]="group.geography">Select all</label>
          </div>
        </div>
        <div class="p-2">
          <label
            *ngFor="let region of group?.regions"
            [for]="region.name"
            class="form-check-label align-items-center mb-2"
            [ngClass]="{ 'text-primary': region.checked }"
            style="margin-bottom: 5px; margin-right: 10px"
          >
            <input
              type="checkbox"
              [id]="region.name"
              [(ngModel)]="region.checked"
              (change)="onChange(region, group)"
              class="form-check-input me-2"
            />
            {{ region.physicalLocation }} ({{ region.name }})
          </label>
        </div>
      </section>
    </div>
  </div>
</div>
